name: shelf_eventsource
description: A shelf handler for Server-Sent Events (SSE).
version: 0.3.0
repository: https://github.com/stevenroose/dart-shelf_eventsource

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  eventsource: ^0.4.0
  shelf: ^1.4.0
  stream_channel: ^2.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  # for the examples:
  shelf_router: ^1.1.3
